### ISSUE TITLE
virtio-win 0.1.185-1 broke spice/qxl automatic screen resizing

### ISSUE THREAD

**Issue by rgl** [virtio-win/virtio-win-pkg-scripts#31]
The upgrade to virtio-win 0.1.185-1 (from virtio-win 0.1.173-9) broke the spice/QXL automatic screen resizing (e.g. when I resize the virt-viewer window the Windows VM guest screen no longer resizes with it).

I'm testing this on a Ubuntu 20.04 host (virt-viewer 7.0; virtual machine manager 2.2.1; libvirt 6.0.0; qemu 4.2) while running a Windows 2019 server (with this month cumulative updates).

The package/vagrant environment that I use to test this is at https://github.com/rgl/windows-vagrant. In concrete, in these lines:

* https://github.com/rgl/windows-vagrant/blob/master/windows-2019.json#L53-L55
* https://github.com/rgl/windows-vagrant/blob/master/Vagrantfile.template#L9-L12
* https://github.com/rgl/windows-vagrant/blob/0593025e078c995ee71d38ea5683dcd08252673a/provision.ps1#L41-L71

**Comment by vrozenfe** [comment]
QXL is under Spice team control. I will ask Yuri to look  into this issue.

**Comment by ybendito** [comment]
@rgl Screen resize is functionality of qxl-wddm-dod and spice agent (usually vdservice). What returns "sc query vdservice"? If you uninstall virtio-win 0.1.185-1 and install back virtio-win 0.1.173-9 does this fix the problem? 
@crobinso What is virtio-win 0.1.185-1 and what it contains, how it is related to qxl-wddm-dod?

**Comment by vrozenfe** [comment]
@ybendito 
spice-qxl-wddm-dod-0.20-0

**Comment by ybendito** [comment]
@vrozenfe Where can I download these virtio-win packages?

**Comment by rgl** [comment]
@ybendito you can download at:

* https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.173-9/virtio-win-0.1.173.iso
* https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.185-1/virtio-win-0.1.185.iso

**Comment by rgl** [comment]
Today I tried everything again from scratch, and it now works correctly with 0.1.185. I do not known why it wasn't working before...

How do I get the version of these tools/drivers on a running system?

For example, vdagent/vdservice.exe file version is 0.9.0, which does not seem to be 0.20 as in spice-qxl-wddm-dod-0.20-0.

**Comment by rgl** [comment]
There is something really odd happening, sometimes the resizing does not work because the vdagent/vdservice.exe are not running at all. For some reason they are not being started, or crash after a while.

**Comment by ybendito** [comment]
Screen resize will never work without vdservice regardless of the version of qxl-wddm-dod.
When vdservice starts it tries to find the qxl-wddm-dod and waits some time for it, if does not succeed to communicate with it, it gets stopped. I've never saw it crashed, but it this happens due to some reason - this should be reported in Event Viewer - System.

**Comment by rgl** [comment]
@ybendito, the problem was that the vdagent service was not being install at all. all the other stuff was in place :-)

the virtio-win-guest-tools.exe installer is supposed to install vdagent, but its currently broken with the error that I've displayed in the screenshot.

**Comment by rgl** [comment]
I've retried this with virtio-win 0.1.189-1 at https://github.com/rgl/windows-vagrant/blob/master/provision-guest-tools-qemu-kvm.ps1#L26-L36 and its now working as expected.

Thank You!
