### ISSUE TITLE
我使用了virtio-win-0.1.190.iso 最新版版本，vioscsi.sys出现黑屏 0xc0000428代码，无法进行GPT分区模式下启动引导

### ISSUE THREAD

**Issue by 1265578519** [virtio-win/virtio-win-pkg-scripts#39]
我使用了virtio-win-0.1.190.iso 最新版版本，vioscsi.sys出现黑屏 0xc0000428代码，无法进行GPT分区模式下启动引导
![image](https://user-images.githubusercontent.com/6442439/109540854-0343f800-7afe-11eb-84c0-9c2db50a2119.png)

如果分区为MBR，则可以正常使用。

**Comment by vrozenfe** [comment]
Are you trying UEFI or what is your guest configuration?
Thanks,
Vadim.

**Comment by 1265578519** [comment]
https://github.com/virtio-win/kvm-guest-drivers-windows/issues/557
问题已经得到解答
