### ISSUE TITLE
Windows 2016 and 2019: Network adapter disappears after executing virtio-win-guest-tools.exe

### ISSUE THREAD

**Issue by rgl** [virtio-win/virtio-win-pkg-scripts#48]
In Windows 2016 and 2019, after installing virtio-win-guest-tools.exe from [virtio-win-0.1.208.iso](https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.208-1/virtio-win-0.1.208.iso) the network stops working.

This happens while I'm building the image with packer from the Windows iso. Windows autounattended correctly finds the drivers and is able to install Windows. But, after Windows is installed, and execute virtio-win-guest-tools.exe is executed, and for some reason, while its running, the network goes down and the network adapter even disappears from Device Manager.

Please note that this worked correctly with [virtio-win-0.1.190.iso](https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.190-1/virtio-win-0.1.190.iso).

Do you have any idea of what might the problem?

PS: It works fine with Windows 2022; but not for 2016 and 2019.

**Comment by rgl** [comment]
From all the `.log` files inside `%SystemRoot%\Inf`, only `C:\Windows\Inf\setupapi.dev.log` seems to have errors. It fails installing the `pvpanic` driver (sorry, but I only have screenshot):

![image](https://user-images.githubusercontent.com/43356/147368102-3fd94108-958c-4a59-b8d1-02a5eda6c175.png)

And it also fails to install (not sure what this is):

![image](https://user-images.githubusercontent.com/43356/147368177-0fde9928-09d0-4c3d-8dd6-1a6e82c3bbbd.png)

**Comment by rgl** [comment]
FYI, this is still not working with virtio-win-0.1.215.iso.

**Comment by TrycsPublic** [comment]
Same problem, bump.

**Comment by YanVugenfirer** [comment]
@kostyanf14 please take a look

**Comment by rgl** [comment]
With virtio-win-0.1.221.iso, Windows 2019 works correctly.

Since I no longer use Windows 2016, this issue is fixed for me. So I'm closing this.
