### ISSUE TITLE
Eats up all memory virtio-win-0.1.208.iso   ProxMOx Qemu 

### ISSUE THREAD

**Issue by C-Magic** [virtio-win/virtio-win-pkg-scripts#51]
![image](https://user-images.githubusercontent.com/59870706/140278116-1ba281ea-2b2e-4a77-b641-9be666d774a1.png)
Windows 10 Pro
Driver 1.208
Eats up all memory

**Comment by vrozenfe** [comment]
Is it a regression comparing to 204?
In any case I would suggest to open a new issue at https://github.com/virtio-win/kvm-guest-drivers-windows
This project is mostly about packaging the virtio-win drivers but not the drivers themselves.

Best,
Vadim.

**Comment by C-Magic** [comment]
sorry, misunderstood

**Comment by C-Magic** [comment]
off topic
