### ISSUE TITLE
0.1.217 Windows 11 MSI/EXE Failed Install

### ISSUE THREAD

**Issue by nickp85** [virtio-win/virtio-win-pkg-scripts#63]
I just attempted to update my drivers in a Windows 11 guest using the x64 0.1.217 MSI and it fails and rolls back. Programs list still shows the old version of the drivers and guest software. After the failure the network adapter had no drivers and would not work. Had to mount the ISO in the VM and manually install the drivers from device manager for network and serial then update SCSI controller. All worked manually but MSI for drivers and EXE for guest tools still won't run. Attaching log file.

Please let me know how I can fix this broken install. Been using the MSI installer for years and from Windows 10 to now Windows 11 upgraded last year. Have updated previously on Windows 11 and worked fine.

[Virtio-win-guest-tools_20220428230549_003_virtio_win_gt_x64.msi.log](https://github.com/virtio-win/virtio-win-pkg-scripts/files/8587946/Virtio-win-guest-tools_20220428230549_003_virtio_win_gt_x64.msi.log)

![image](https://user-images.githubusercontent.com/59027847/165882099-17bb18aa-f00c-477d-a363-8fb203871779.png)
![image](https://user-images.githubusercontent.com/59027847/165882122-0a44dd65-edfc-41bc-9cbe-31614e70db32.png)

**Comment by nickp85** [comment]
I see there are open issues for this, I'm closing mine. OK for now with manual driver install

**Comment by ChristophSchmidpeter** [comment]
It fails with a rollback for me as well

**Comment by ChristophSchmidpeter** [comment]
@nickp85 Why has the issue been closed?

**Comment by xerz-one** [comment]
@ChristophSchmidpeter I think it was closed because #33 and #60 are open already

**Comment by ChristophSchmidpeter** [comment]
@xerz-one I see, thanks for the info!
