### ISSUE TITLE
Download links broken

### ISSUE THREAD

**Issue by littleboot** [virtio-win/virtio-win-pkg-scripts#72]
Update the issue seems to be resolved and I'm now able to download the files again. Optional fix: provide a mirror for these files. 

Non of the provided links are working, it seems the website fedorapeople is not working.
[Stable virtio-win ISO](https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/stable-virtio/virtio-win.iso)
    [Stable virtio-win RPM](https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/stable-virtio/virtio-win.noarch.rpm)
    [Latest virtio-win ISO](https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/latest-virtio/virtio-win.iso)
    [Latest virtio-win RPM](https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/latest-virtio/virtio-win.noarch.rpm)
    [Latest virtio-win-guest-tools.exe](https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/latest-virtio/virtio-win-guest-tools.exe)
    [virtio-win direct-downloads full archive](https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/) with links to other bits like qemu-ga, a changelog, etc.
```
fedorapeople.org has a security policy called HTTP Strict Transport Security (HSTS), which means that Firefox can only connect to it securely. You can’t add an exception to visit this site.
```

**Comment by YanVugenfirer** [comment]
Hi @littleboot ,

They work now. 

Best regards,
Yan.
