### ISSUE TITLE
Installer placement on the ISO filesystem can lead to user confusion

### ISSUE THREAD

**Issue by jedenastka** [virtio-win/virtio-win-pkg-scripts#76]
**Is your feature request related to a problem? Please describe.**
The `virtio-win-gt-x64.msi` and `virtio-win-gt-x86.msi` installers are in the root directory of the ISO filesystem, even though they don't install all drivers like the `virtio-win-guest-tools.exe` installer does. That can create confusion among new users and cause them to install the wrong file.

**Describe the solution you'd like**
Move the `virtio-*.msi` installers to a subdirectory so it's clear the `virtio-win-guest-tools.exe` installer should be ran.

**Describe alternatives you've considered**
Make the `virtio-*.msi` installers return an error directing to run `virtio-win-guest-tools.exe` if they are ran directly by the user (by using a command line switch for example; not sure if it's technically possible or not).

**Additional context**
None.

**Comment by vrozenfe** [comment]
In addition to virtio-win msi the virtio-win tools bundle installs qemu guest and spice agents. 
But we are planing to remove spice from the bundle in the next release.

**Comment by rgl** [comment]
FWIW, the spice agent was dropped in https://github.com/virtio-win/virtio-win-guest-tools-installer/commit/926dbaca56b03507ecdb6c624e3bb95204f6904a

@vrozenfe can you please explain why it was removed?

**Comment by vrozenfe** [comment]
@rgl 
The short answer is because we (Red Hat) don't support SPICE/qxl anymore.

The long answer is because currently we use almost the same building scripts and infrastructure to build both 
upstream and downstream virtio-win packages. And since our downstream package doesn't need SPICE and QXL both of them were removed from the bundle. The same changes were done for both downstream and upstream packages.

Since this question was asked several times in the past, it looks as some upstream users still prefer to have SPICE and QXL components installed automatically. I will try to bring them back in the upstream installer in the next or one of the following releases.

Vadim.

**Comment by rgl** [comment]
@vrozenfe, that would be nice! thank you!

Is qxl/spice being replaced with something else?

Is there other combination that has an equivalent feature set (e.g. resizable desktop, copy&paste)?

**Comment by vrozenfe** [comment]
@rgl 
qxl can be replaced with virtio-gpu (viogpudo.sys). There is no replacement for spice/copy&paste feature,
But dynamic desktop resolution feature can be activated by installing vgpusrv service. It should work for 
VMs running locally and over VNC.

Cheers,
Vadim.

**Comment by benjaminsabatini** [comment]
This was a super weird decision, almost intentionally evil. For the longest time, I had no idea why my Windows guest wasn't performing correctly.

**Comment by rgl** [comment]
can you please confirm that the spice agent, removed in https://github.com/virtio-win/virtio-win-guest-tools-installer/commit/926dbaca56b03507ecdb6c624e3bb95204f6904a, was re-introduced in https://github.com/virtio-win/virtio-win-pkg-scripts/commit/62c74d124bac4bf8422bf54a97a10702a8f5b938 and included in https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.262-2/? if so, maybe this issue can be closed?

**Comment by vrozenfe** [comment]
@rgl 
conformed. 
spice and qxldod are back now and included in virtio-win bundle.

Vadim.

**Comment by vrozenfe** [comment]
Closing this issue as resolved.
