### ISSUE TITLE
Graphics makes VM lag out.

### ISSUE THREAD

**Issue by jon-bit** [virtio-win/virtio-win-pkg-scripts#78]
**Describe the bug**
I install the RPM packages on my fedora box and not super tux cart and steam lag and hang every time I open them.

**To Reproduce**
install the RPM packages on the host and the guest. Install steam on the Gust (should be Linux) and then super tux kart. Nether of them should work. Both should hang shortly after lunching.

**Expected behavior**
They launch and work "semi" good. 

**Screenshots**

![Screenshot from 2023-06-27 02-18-16](https://github.com/virtio-win/virtio-win-pkg-scripts/assets/59271817/ea0820ba-6132-4276-b666-7e786e4c0f09)

**Host:**
 - Disto: Fedora 38
 - Kernel version: 6.3.8
 - QEMU version: 7.2.1
 - QEMU command line: ?
 - libvirt version: 9.0.0
 - libvirt XML file: ?

**Guest:**
 - Fedora
 - 0.1.229

**Additional context**

**Comment by YanVugenfirer** [comment]
@jon-bit Sorry, this is a project for Windows guest drivers.
If you are using Linux guest, then other mailing lists or repositories (github\gitlab) are more appropriate.
I am not sure why you try to install virtio-win package on Fedora guest.

Thanks,
Yan.
