### ISSUE TITLE
Program virtio-win-guest-tools.exe fails to install into the guest

### ISSUE THREAD

**Issue by Folaht** [virtio-win/virtio-win-pkg-scripts#87]
**Describe the bug**
Same as https://github.com/virtio-win/virtio-win-pkg-scripts/issues/60 
except the temporary solution doesn't work.

**To Reproduce**
Regular install

**Expected behavior**
Complete installation of virtio-win-guest-tools.

**Screenshots**
![image](https://github.com/virtio-win/virtio-win-pkg-scripts/assets/9342090/68fe951b-9846-4835-8b94-e0747b9c3ab3)

**Host:**
- Distro: Manjaro Linux
- Kernel version: 6.1.69-1-MANJARO x86_64
- QEMU version: 8.2.0-2
- QEMU command line: None, I start virt-manager
- libvirt version: 1:9 10.0-1
- libvirt XML
```
<channel type="spicevmc">
  <target type="virtio" name="com.redhat.spice.0" state="disconnected"/>
  <alias name="channel0"/>
  <address type="virtio-serial" controller="0" bus="0" port="1"/>
</channel>
```

**Guest:**
 - Microsoft Windows 11 Pro
- 10.0.22000 Build 22000

**Additional context**

https://privatebin.io/?2edd40ce1daacf0d#FZe812pPpjHbUAN3fTeafPCuLi3g4tGSXSoYXBMq2H8B

**Comment by YanVugenfirer** [comment]
@Folaht which Windows 11 release is it?

**Comment by Folaht** [comment]
You mean wether it's Home or Pro?  
It's Pro. I updated the question.

**Comment by YanVugenfirer** [comment]
I mean, is it 22H2, 23H3, or something else?

**Comment by Folaht** [comment]
21H2

**Comment by vrozenfe** [comment]
@Folaht 
[0980:01B4][2024-01-23T22:34:05]i360: Creating a system restore point.
[0980:01B4][2024-01-23T22:34:05]w363: Could not create system restore point, error: 0x80070422. Continuing...

What is your system's Recovery partition size?

**Comment by Folaht** [comment]
I'm closing this issue.  
For whatever reason I can't get Windows to even update, so I will reinstall windows 11.  
I've been able save all significant files by downloading an openssh server and turning that on.

**Comment by AlexFolland** [comment]
I wanted to see if I am seeing the same issue as you saw, but the paste expired.

**Comment by vrozenfe** [comment]
@AlexFolland 
can you see errors 0x80070643 and 0x80070422 in the msi installation log file?
Vadim.

**Comment by AlexFolland** [comment]
I did originally have a restore point failure log entry, but I solved that by configuring and enabling restore points in Windows.

**Comment by AlexFolland** [comment]
Creating restore points works, as can be seen in the log screenshot I pasted, so that's not the cause of the problem.
