### ISSUE TITLE
[Question] Options for CMD install (virtio-win-guest-tools.exe)

### ISSUE THREAD

**Issue by abceleung** [virtio-win/virtio-win-pkg-scripts#90]
This shows when I run `virtio-win-guest-tools.exe /?`:

![Capture](https://github.com/virtio-win/virtio-win-pkg-scripts/assets/82202780/503ea7b4-78cb-4951-91d2-b6c415e41308)

Are these all the possible options? I can't enlarge the window so I am not sure

**Comment by vrozenfe** [comment]
Hi @abceleung 
Most (if not all) flags should work. 
Did you meet any problem running the bundle with any of these flags?

Best,
Vadim.

**Comment by abceleung** [comment]
> Hi @abceleung Most (if not all) flags should work. Did you meet any problem running the bundle with any of these flags?
> 
> Best, Vadim.

Hi, I didn't encounter any issue, just want to know is there any extra flags not shown in the image (as you can see, the bottom part is hidden due to window size).

**Comment by vrozenfe** [comment]
only the standard MS installer command line options https://learn.microsoft.com/en-us/windows/win32/msi/standard-installer-command-line-options

Best,
Vadim.
