### ISSUE TITLE
Clarification request: Is README section "virtio-win driver signatures" still correct?

### ISSUE THREAD

**Issue by robert-scheck** [virtio-win/virtio-win-pkg-scripts#91]
As of writing, `README.md` says in section "virtio-win driver signatures":

> All the Windows binaries are from builds done on Red Hat’s internal build system, which are generated using publicly available code. Windows 8+ drivers are cryptographically signed with Red Hat’s [test signature](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/test-signing) Windows 10+ drivers are signed with [Microsoft attestation signature](https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/code-signing-attestation). However they are not signed with Microsoft’s [WHQL signature](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/whql-release-signature). WHQL signed builds are only available with a paid RHEL subscription.

Is this section still correct? There are (3rd-party) sites claiming that already since version 0.1.204 (July 2021), the virtio-win drivers would be WHQL-signed. May I kindly ask you to comment on this and/or to clarify the current status, please?

**Comment by YanVugenfirer** [comment]
@robert-scheck 
The drivers are not WHQL signed, but rather "attestation" signed https://learn.microsoft.com/en-us/windows-hardware/drivers/dashboard/code-signing-attestation. Those can be used for secure boot.
There can be a confusion between "attestation" signing and WHQL signing, because both are coming from MS.

**Comment by robert-scheck** [comment]
@YanVugenfirer, thank you very much for the clarification!
